'use client';

import { useRef, useState } from 'react';
import { ScrollText } from 'lucide-react';

interface TermsBoxProps {
  onAgreedChange: (agreed: boolean) => void;
  agreed: boolean;
  /** Checkbox label — defaults to the inviter wording; candidates pass their own. */
  label?: React.ReactNode;
}

export default function TermsBox({ onAgreedChange, agreed, label }: TermsBoxProps) {
  const [scrolled, setScrolled] = useState(false);
  const tcRef = useRef<HTMLDivElement>(null);

  function onScroll() {
    const el = tcRef.current;
    if (!el) return;
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 24) setScrolled(true);
  }

  return (
    <div style={{ marginBottom: 4 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <ScrollText size={14} color="var(--ink-2)" />
        <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink)' }}>
          Review T&amp;C
        </span>
        <span style={{ marginLeft: 'auto', fontSize: 11.5, color: scrolled ? '#059669' : 'var(--ink-2)' }}>
          {scrolled ? '✓ Scrolled to end' : 'Scroll to read all'}
        </span>
      </div>

      <p style={{ fontSize: 11.5, color: 'var(--ink-2)', marginBottom: 8 }}>
        Note: Please scroll to read the full Terms &amp; Conditions before continuing.
      </p>

      {/* Scrollable box */}
      <div
        ref={tcRef}
        onScroll={onScroll}
        style={{
          height: 240, overflowY: 'auto', border: '1px solid var(--rule)',
          borderRadius: 8, padding: '14px 16px', background: 'var(--paper)',
          fontSize: 12, lineHeight: 1.7, color: 'var(--ink-2)', scrollbarWidth: 'thin',
        }}
      >
        <h3 style={{ fontSize: 13, fontWeight: 700, color: 'var(--ink)', marginBottom: 10 }}>
          Terms and Conditions
        </h3>
        <p style={{ marginBottom: 10, fontSize: 11.5 }}>
          Issued by <strong style={{ color: 'var(--ink)' }}>Handy Online Solution Private Limited</strong>,
          a company incorporated under the Companies Act, 2013, with its registered office at
          D2-12A02, Parsvnath Exotica, Sector 53, Golf Course Road, Gurgaon, Haryana – 122011
          and corporate office at 1st Floor, Plot No. 34, Sector 44, Gurugram, Haryana – 122003
          (<strong style={{ color: 'var(--ink)' }}>"Company"</strong>).
          By clicking "I Agree" or by accessing or using the Platform, you acknowledge that you
          have read, understood, and agree to be bound by these Terms.
        </p>

        <Section n="1" title="Definitions">
          <Clause n="1.1"><strong>"Platform"</strong> refers to the website, mobile application, dashboard, software systems, and associated technology infrastructure that the Company operates to facilitate background verification services.</Clause>
          <Clause n="1.2"><strong>"User"</strong> means any individual who accesses the Platform and requests or initiates a background verification through it.</Clause>
          <Clause n="1.3"><strong>"Candidate / Data Principal"</strong> means the individual whose personal information, identity details, or other data is submitted by the User for the purpose of conducting a background verification.</Clause>
          <Clause n="1.4"><strong>"Verification Services"</strong> means the background checks requested by the User and facilitated through the Platform using information sourced from publicly available records, lawfully accessible databases, or other permissible channels.</Clause>
          <Clause n="1.5"><strong>"Report"</strong> means the output generated by the Platform following completion of the selected verification checks.</Clause>
        </Section>

        <Section n="2" title="Nature of Services">
          <Clause n="2.1">The Company provides a technology platform that enables Users to initiate background verification checks for lawful personal purposes, including domestic employment, personal safety, tenant screening, or matrimonial evaluation.</Clause>
          <Clause n="2.2">The Company operates solely as a facilitator and data processor, handling personal information only to the extent required to deliver the Verification Services requested.</Clause>
          <Clause n="2.3">The Company does not independently determine the purpose behind a verification request and does not use personal data for any purpose beyond delivering the requested services.</Clause>
          <Clause n="2.4">The Company is not an investigative agency and does not undertake independent investigations beyond the scope of the checks selected by the User.</Clause>
        </Section>

        <Section n="3" title="Consent of the Candidate">
          <Clause n="3.1">The User must obtain prior, explicit, informed, and voluntary consent from the Candidate before submitting the Candidate's data on the Platform or initiating any verification request.</Clause>
          <Clause n="3.2">Such consent must clearly inform the Candidate that: (a) their personal data will be submitted to the Platform; (b) background verification checks will be conducted; and (c) a Report may be compiled and shared with the User.</Clause>
          <Clause n="3.3">The User warrants that the consent obtained complies with all applicable data protection and privacy laws, including the Digital Personal Data Protection Act, 2023.</Clause>
          <Clause n="3.4">The Company relies entirely on the User's representations regarding the existence and validity of such consent and does not independently verify the same.</Clause>
        </Section>

        <Section n="4" title="User Representations and Warranties">
          <p style={{ marginBottom: 6 }}>By using the Platform, the User expressly represents, warrants, and undertakes that:</p>
          <ul style={{ paddingLeft: 18 }}>
            {[
              'valid, informed, and lawful consent has been obtained from the Candidate before initiating any verification;',
              'the Candidate has been duly informed that their personal data will be processed for background verification purposes;',
              "all information provided in relation to the Candidate is true, accurate, and complete to the best of the User's knowledge;",
              'the User will not provide false, fabricated, or incorrect contact details of the Candidate;',
              'the User will not coerce, misrepresent, or improperly induce the Candidate to provide consent;',
              'the User will use the Platform strictly in compliance with all applicable laws and in accordance with these Terms.',
            ].map((item, i) => <li key={i} style={{ marginBottom: 4 }}>{item}</li>)}
          </ul>
          <p style={{ marginTop: 6, fontSize: 11, fontWeight: 600, color: 'var(--ink)' }}>
            Important: The Company relies entirely on the User's representations and does not independently verify whether consent has been obtained from the Candidate.
          </p>
        </Section>

        <Section n="5" title="Notice to Candidate">
          <Clause n="5.1">Upon initiation of a verification request, the Candidate may receive a notification informing them that a background check has been requested.</Clause>
          <Clause n="5.2">The Candidate may raise an objection or request suspension of the process if they believe the request was initiated without their knowledge or consent.</Clause>
          <Clause n="5.3">Upon receiving a valid objection, the Company reserves the right to suspend or discontinue the verification process at its sole discretion pending further review.</Clause>
        </Section>

        <Section n="6" title="Limitation of Verification">
          <Clause n="6.1">Verification Services are carried out on the basis of: (a) information provided by the User; and/or (b) publicly available, third-party, or lawfully accessible sources.</Clause>
          <Clause n="6.2">The Company does not guarantee: (a) the accuracy, completeness, or reliability of information obtained from third-party or public sources; or (b) the future conduct, behaviour, or suitability of the Candidate.</Clause>
          <Clause n="6.3">Reports reflect information available as of the date of verification and may not capture subsequent developments, changes, or updates.</Clause>
        </Section>

        <Section n="7" title="Prohibited Uses">
          <p style={{ marginBottom: 6 }}>The User shall not, under any circumstances:</p>
          <ul style={{ paddingLeft: 18 }}>
            {[
              'share, publish, or disclose any Report or part thereof to any unauthorised third party;',
              'use the Report for purposes of harassment, discrimination, defamation, stalking, or any other unlawful purpose;',
              'treat the Report as conclusive evidence of criminal conduct, character, reputation, or suitability of any individual;',
              'use the Platform in violation of any applicable law, rule, or regulation.',
            ].map((item, i) => <li key={i} style={{ marginBottom: 4 }}>{item}</li>)}
          </ul>
        </Section>

        <Section n="8" title="Data Retention">
          <p>The Company retains personal data only for the period reasonably necessary to: (a) deliver the requested Verification Services; (b) comply with applicable legal or regulatory obligations; and (c) address audit, security, or dispute resolution requirements. Upon expiry of the applicable retention period, personal data will be deleted or anonymised in accordance with applicable law.</p>
        </Section>

        <Section n="9" title="Limitation of Liability">
          <p style={{ marginBottom: 6 }}>To the maximum extent permitted by applicable law, the Company shall not be liable for any indirect, incidental, special, or consequential damages arising out of or related to the use of the Platform, even if advised of the possibility of such damages.</p>
          <p>In no event shall the Company's total aggregate liability exceed the total amount actually paid by the User to the Company in connection with the transaction giving rise to the claim.</p>
        </Section>

        <Section n="10" title="Indemnity">
          <Clause n="10.1">The User agrees to fully indemnify and hold the Company harmless against any losses, costs, or damages (including reasonable legal fees) arising from: (a) failure to obtain valid consent from the Candidate; (b) misuse of Reports or the Platform; (c) violation of any applicable law; or (d) any breach of these Terms.</Clause>
          <Clause n="10.2">The Company may participate in the defence of any such claim at its discretion. No settlement adversely affecting the Company shall be made without its prior written approval.</Clause>
        </Section>

        <Section n="11" title="Termination">
          <p>The Company reserves the right to suspend, restrict, or terminate any User's access to the Platform, with or without prior notice, where misuse, misrepresentation, or legal or regulatory risk is detected or reasonably suspected.</p>
        </Section>

        <Section n="12" title="Governing Law and Jurisdiction">
          <p>These Terms are governed by and construed in accordance with the laws of India. The courts at Gurugram, Haryana shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms or the use of the Platform.</p>
        </Section>

        <p style={{ marginTop: 14, fontSize: 11, color: 'var(--ink-2)', fontStyle: 'italic' }}>
          Last updated: {new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
        </p>
      </div>

      {/* Agree checkbox */}
      <label style={{
        display: 'flex', alignItems: 'flex-start', gap: 10, marginTop: 10,
        cursor: scrolled ? 'pointer' : 'not-allowed', opacity: scrolled ? 1 : 0.45,
      }}>
        <input
          type="checkbox"
          checked={agreed}
          disabled={!scrolled}
          onChange={e => onAgreedChange(e.target.checked)}
          style={{ marginTop: 2, flexShrink: 0 }}
        />
        <span style={{ fontSize: 12.5, color: 'var(--ink)', lineHeight: 1.55 }}>
          {label ?? (
            <>
              I confirm that I have obtained the candidate's consent and I agree to
              the Terms &amp; Conditions of Handy Online Solution Private Limited,
              operating the Assurio platform.
            </>
          )}
        </span>
      </label>
      {!scrolled && (
        <p style={{ fontSize: 11, color: 'var(--ink-2)', marginTop: 5 }}>
          ↑ Scroll to the end of the Terms to enable this checkbox.
        </p>
      )}
    </div>
  );
}

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 12 }}>
      <h4 style={{ fontSize: 11.5, fontWeight: 700, color: 'var(--ink)', marginBottom: 5, textTransform: 'uppercase', letterSpacing: '0.06em' }}>
        {n}. {title}
      </h4>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>{children}</div>
    </div>
  );
}

function Clause({ n, children }: { n: string; children: React.ReactNode }) {
  return (
    <p style={{ margin: 0 }}>
      <strong style={{ color: 'var(--ink)' }}>{n}</strong> {children}
    </p>
  );
}
