'use client';

/**
 * Internal per-client invoices ledger — modelled on Recriauth's internal client
 * invoices view, but read-only to match our billing logic: the client pays
 * (Razorpay) and the invoice is generated instantly, so there is no pay-later /
 * mark-paid / void lifecycle. Filter row (Status + Amount) + search, and the
 * invoices table (Invoice ID / Generated by / Status / Payment Mode / Date /
 * Amount) with pagination.
 */
import { useCallback, useEffect, useState } from 'react';
import {
  FilterRow,
  Input,
  Pagination,
  Table,
  TableBody,
  TableCell,
  TableHeader,
  TableHeaderCell,
  TableRow,
  Tag,
  toast,
} from '@/shared/components/ui';
import {
  adminClientInvoices,
  type ClientInvoiceRow,
  type InvoiceBusinessStatus,
  type InvoicePaymentMethod,
} from '../../../lib/api';
import InvoiceDetailPanel from '../../../components/InvoiceDetailPanel';

const PAGE_SIZE = 10;

const STATUS_TAG: Record<
  InvoiceBusinessStatus,
  { label: string; variant: 'Success' | 'Warning' | 'Default' }
> = {
  DUE: { label: 'Payment Due', variant: 'Warning' },
  PAID: { label: 'Paid', variant: 'Success' },
  VOID: { label: 'Void', variant: 'Default' },
};

const METHOD_LABELS: Record<InvoicePaymentMethod, string> = {
  BANK_REMITTANCE: 'Bank Remittance',
  BANK_TRANSFER: 'Bank Transfer',
  CASH: 'Cash',
  CHEQUE: 'Cheque',
  CREDIT_CARD: 'Credit Card',
  UPI: 'UPI',
};

const AMOUNT_BUCKETS = [
  { value: '0-1000', label: '₹0 – ₹1,000' },
  { value: '1000-5000', label: '₹1,000 – ₹5,000' },
  { value: '5000-10000', label: '₹5,000 – ₹10,000' },
  { value: '10000-25000', label: '₹10,000 – ₹25,000' },
  { value: '25000-50000', label: '₹25,000 – ₹50,000' },
  { value: '50000-', label: '₹50,000+' },
];

function fmtAmount(s: string): string {
  return `₹${Number(s).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}
function fmtDate(iso?: string | null): string {
  if (!iso) return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}
/** Payment mode — instant-paid invoices settle via Razorpay. */
function paymentModeLabel(inv: ClientInvoiceRow): string {
  if (inv.paymentMethod) return METHOD_LABELS[inv.paymentMethod] ?? inv.paymentMethod;
  if (inv.kind === 'INSTANT_PAID' && inv.businessStatus === 'PAID') return 'Razorpay';
  return '—';
}

export default function InvoicesTab({ clientId }: { clientId: string }) {
  const [rows, setRows] = useState<ClientInvoiceRow[]>([]);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [businessStatus, setBusinessStatus] = useState<InvoiceBusinessStatus | ''>('');
  const [amountBucket, setAmountBucket] = useState('');
  const [search, setSearch] = useState('');
  const [searchInput, setSearchInput] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [minAmount, maxAmount] = amountBucket ? amountBucket.split('-') : ['', ''];
      const res = await adminClientInvoices('', clientId, {
        businessStatus: businessStatus || undefined,
        search: search.trim() || undefined,
        minAmount: minAmount || undefined,
        maxAmount: maxAmount || undefined,
        page,
        pageSize: PAGE_SIZE,
      });
      setRows(res.data);
      setTotalPages(res.meta.totalPages);
      setTotal(res.meta.totalItems);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to load invoices');
    } finally {
      setLoading(false);
    }
  }, [clientId, businessStatus, amountBucket, search, page]);

  useEffect(() => {
    void load();
  }, [load]);

  // Debounced search → page 1.
  useEffect(() => {
    const t = setTimeout(() => {
      setPage(1);
      setSearch(searchInput);
    }, 350);
    return () => clearTimeout(t);
  }, [searchInput]);

  return (
    <div>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <FilterRow
          filters={[
            {
              id: 'business-status',
              label: 'Status',
              options: [
                { value: 'PAID', label: 'Paid' },
                { value: 'DUE', label: 'Payment Due' },
                { value: 'VOID', label: 'Void' },
              ],
              selectedValues: businessStatus ? [businessStatus] : [],
              onSelectionChange: (values) => {
                setPage(1);
                setBusinessStatus(
                  (values[values.length - 1] as InvoiceBusinessStatus) || '',
                );
              },
            },
            {
              id: 'amount-range',
              label: 'Amount Range',
              options: AMOUNT_BUCKETS,
              selectedValues: amountBucket ? [amountBucket] : [],
              onSelectionChange: (values) => {
                setPage(1);
                setAmountBucket(values[values.length - 1] ?? '');
              },
            },
          ]}
          onClearAll={() => {
            setPage(1);
            setBusinessStatus('');
            setAmountBucket('');
          }}
        />
        <div className="w-full sm:w-[280px]">
          <Input
            placeholder="Search invoice ID"
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
          />
        </div>
      </div>

      <p className="mb-2 text-body-sm text-text-placeholder">
        Showing {rows.length} out of {total}
      </p>

      <Table bordered className="bg-white">
        <TableHeader>
          <TableRow>
            <TableHeaderCell label="Invoice ID" />
            <TableHeaderCell label="Generated by" className="cd-col-hide" />
            <TableHeaderCell label="Status" />
            <TableHeaderCell label="Payment Mode" className="cd-col-hide" />
            <TableHeaderCell label="Date" className="cd-col-hide" />
            <TableHeaderCell label="Amount" />
          </TableRow>
        </TableHeader>
        <TableBody>
          {loading ? (
            <TableRow>
              <TableCell
                colSpan={6}
                className="text-center"
                value={<span className="text-text-placeholder">Loading…</span>}
              />
            </TableRow>
          ) : rows.length === 0 ? (
            <TableRow>
              <TableCell
                colSpan={6}
                className="text-center"
                value={
                  <span className="text-text-placeholder">No invoices yet.</span>
                }
              />
            </TableRow>
          ) : (
            rows.map((inv) => {
              const tag = STATUS_TAG[inv.businessStatus];
              return (
                <TableRow key={inv.id} hoverable>
                  <TableCell
                    type="primary"
                    primaryText={inv.documentNumber}
                    showSubtext={false}
                    onPrimaryClick={() => setSelectedId(inv.id)}
                  />
                  <TableCell
                    className="cd-col-hide"
                    value={inv.initiatedBy?.name ?? 'System'}
                  />
                  <TableCell value={<Tag label={tag.label} variant={tag.variant} />} />
                  <TableCell className="cd-col-hide" value={paymentModeLabel(inv)} />
                  <TableCell className="cd-col-hide" value={fmtDate(inv.documentDate)} />
                  <TableCell value={fmtAmount(inv.totalAmount)} />
                </TableRow>
              );
            })
          )}
        </TableBody>
      </Table>

      {totalPages > 1 && (
        <div className="mt-3">
          <Pagination
            currentPage={page}
            totalPages={totalPages}
            onPageChange={setPage}
            pageSize={PAGE_SIZE}
          />
        </div>
      )}

      <InvoiceDetailPanel
        invoiceId={selectedId}
        onClose={() => setSelectedId(null)}
      />
    </div>
  );
}
